// redux/action/actionTypes.js
export const FETCH_USER_LOGIN_SUCCESS = "FETCH_USER_LOGIN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";


// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_QTY = "UPDATE_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const FETCH_CART = "FETCH_CART";
export const SET_CART_ERROR = "SET_CART_ERROR";
export const SET_CART_LOADING = "SET_CART_LOADING";
export const SET_CART_COUNT = "SET_CART_COUNT";
export const CONFIRM_COD_SUCCESS = "CONFIRM_COD_SUCCESS";
export const CONFIRM_COD_FAIL = "CONFIRM_COD_FAIL";
export const CHECKOUT_COD_SUCCESS = "CHECKOUT_COD_SUCCESS";
export const CHECKOUT_COD_FAIL = "CHECKOUT_COD_FAIL";
export const RESET_CART = "RESET_CART";

// Payment
export const CREATE_VNPAY_ORDER_SUCCESS = "CREATE_VNPAY_ORDER_SUCCESS";
export const CREATE_VNPAY_ORDER_FAIL = "CREATE_VNPAY_ORDER_FAIL";


// src/redux/actions/favoriteActionTypes.js
export const LOAD_FAVORITES = "LOAD_FAVORITES";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const CHECK_FAVORITE = "CHECK_FAVORITE";
export const FAVORITE_ERROR = "FAVORITE_ERROR";
export const FAVORITE_LOADING = "FAVORITE_LOADING";


// Notifications
export const FETCH_NOTIFICATIONS_SUCCESS = "FETCH_NOTIFICATIONS_SUCCESS";
export const FETCH_NOTIFICATIONS_FAIL = "FETCH_NOTIFICATIONS_FAIL";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const MARK_NOTIFICATION_READ = "MARK_NOTIFICATION_READ";
export const MARK_ALL_NOTIFICATIONS_READ = "MARK_ALL_NOTIFICATIONS_READ";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const SET_UNREAD_COUNT = "SET_UNREAD_COUNT";
export const NOTIFICATION_LOADING = "NOTIFICATION_LOADING";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";

// Chat
export const FETCH_CHATS_SUCCESS = "FETCH_CHATS_SUCCESS";
export const FETCH_CHATS_FAIL = "FETCH_CHATS_FAIL";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const JOIN_CHAT = "JOIN_CHAT";
export const LEAVE_CHAT = "LEAVE_CHAT";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const MARK_MESSAGES_READ = "MARK_MESSAGES_READ";
export const SET_CURRENT_CHAT = "SET_CURRENT_CHAT";
export const CHAT_LOADING = "CHAT_LOADING";
export const CHAT_ERROR = "CHAT_ERROR";

// WebSocket
export const WEBSOCKET_CONNECTED = "WEBSOCKET_CONNECTED";
export const WEBSOCKET_DISCONNECTED = "WEBSOCKET_DISCONNECTED";
export const WEBSOCKET_ERROR = "WEBSOCKET_ERROR";