// redux/action/actionTypes.js
export const FETCH_USER_LOGIN_SUCCESS = "FETCH_USER_LOGIN_SUCCESS";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";


// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_QTY = "UPDATE_QTY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const FETCH_CART = "FETCH_CART";
export const SET_CART_ERROR = "SET_CART_ERROR";
export const SET_CART_LOADING = "SET_CART_LOADING";
export const SET_CART_COUNT = "SET_CART_COUNT";
export const CONFIRM_COD_SUCCESS = "CONFIRM_COD_SUCCESS";
export const CONFIRM_COD_FAIL = "CONFIRM_COD_FAIL";
export const CHECKOUT_COD_SUCCESS = "CHECKOUT_COD_SUCCESS";
export const CHECKOUT_COD_FAIL = "CHECKOUT_COD_FAIL";
export const RESET_CART = "RESET_CART";

// Payment
export const CREATE_VNPAY_ORDER_SUCCESS = "CREATE_VNPAY_ORDER_SUCCESS";
export const CREATE_VNPAY_ORDER_FAIL = "CREATE_VNPAY_ORDER_FAIL";


// src/redux/actions/favoriteActionTypes.js
export const LOAD_FAVORITES = "LOAD_FAVORITES";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const CHECK_FAVORITE = "CHECK_FAVORITE";
export const FAVORITE_ERROR = "FAVORITE_ERROR";
export const FAVORITE_LOADING = "FAVORITE_LOADING";
